use_frameworks!

target 'SycKit_Example' do
  #pod 'SycKit', :path => '../'
  pod 'SycKit/Foundation', :path => '../' # core + foundation
  pod 'SycKit/UI', :path => '../' # core + ui

  
#  pod 'Reusable' # 注册/获取 cell
  pod 'SnapKit' # 布局
  pod 'MJRefresh' # 下拉刷新
  
  target 'SycKit_Tests' do
    inherit! :search_paths

  end
end
