use_frameworks!

target 'SycKit_Example' do
  #pod 'SycKit', :path => '../'
  pod 'SycKit/Foundation', :path => '../' # core + foundation
  pod 'SycKit/UI', :path => '../' # core + ui

  
  pod 'SnapKit' # 布局
  pod 'MJRefresh' # 下拉刷新
  
  # rx
  pod 'RxSwift' # rx
  pod 'RxCocoa' # 将UIKit中很多视图控件的很多属性值封装成了 Observable
  pod 'NSObject+Rx' # rx.disposeBag 无需 let disposeBag = DisposeBag()
  pod 'RxDataSources' # data source
  
  
  target 'SycKit_Tests' do
    inherit! :search_paths

  end
end
